### ISSUE TITLE
Spinani SSR rele

### ISSUE THREAD

**Issue by pulss** [yardee/ha-wattrouter#13]
Dobrý den,
senzory vsechny nactu, ale nevim jak na ovladani SSR vystupu, Poradite?
Dekuji Slany

**Comment by yardee** [comment]
Dobrý den, 
nastvení SSR je potřeba přes službu modbus: write to register. Nejdříve je potřeba nastavit modbus hub pro wattrouter. Viz. https://www.home-assistant.io/integrations/modbus/
Nastavení mám takto:
```
modbus:
  - name: "wattrouter_modbus"
    type: tcp
    host: 192.168.0.200
    port: 502
```
Pro zapsání potřebujete adresu, podle operace co chcete udělat (viz popis v manálu https://solarcontrols.cz/archives/eshop/WATTrouterMx_CZ.pdf) a hodnotu. Jen je potřeba to volat opakovaně, protože wattrouter jinak hodnotu resetuje. 
V integraci zatím podporu pro modbus nemám, protože jsem to nepotřeboval :-). Až bude čas, můžu zkusit dodělat
